### ISSUE TITLE
EIT project

### ISSUE THREAD

**Issue by oxes500** [EIT-team/ScouseTom#46]
Hello, i would like to ask you, is it possible to use your codes to make arduino EIT device. I'm studying biomedical engineering in my project i need to make it. So could you be so king to explain how it would be possible and what i need.

Thank you.
I look forward to hearing from you.

**Comment by Jimbles** [comment]
Hey,
Yes everything is inside the repository. The checklist in the readme details what you will need

* Two commercial components *
- [Keithley 6221](http://www.tek.com/keithley-low-level-sensitive-and-specialty-instruments/keithley-ultra-sensitive-current-sources-seri) Current source
- EEG system with sufficient bandwidth. The [Biosemi](http://www.biosemi.com/) and  [actiCHamp](http://www.brainvision.com/actichamp.html0) have been used so far, and likely the [gtec](http://www.gtec.at/) or the [Open-Ephys](http://www.open-ephys.org/) will work too

* Custom PCBs and an arduino *
- [Arduino Due](https://www.arduino.cc/en/Main/arduinoBoardDue) For the controller
- [Arduino Switch Board](./src/schematics/Ard_Shield) This controls the current source and the timing of switching current injection pairs
- [Switch Network](./src/schematics/ScouseTom_SwitchNetwork) At least one, each for 37 channels. This connects the current source to the EEG system and the electrodes

This system is primarily aimed at research, and is thus not the cheapest system. If you wanted the lowest cost complete EIT system, then its probably the [SwissTom Pioneer Set](http://www.swisstom.com/en/products/pioneer-set)
