### ISSUE TITLE
ScouseTom Operating Query

### ISSUE THREAD

**Issue by twilliams6** [EIT-team/ScouseTom#47]
Hello,

I tried to email yourselves with my query to the email given (medphys.eit-group@ucl.ac.uk), but unfortunately it appears that my email was denied as you only seem to be able to accept messages from people in your organisation.

So I will post my query below instead.

Dear Sir/Madam,

I am a PhD student at Loughborough University and am interested in making a ScouseTom system. I was wondering what frequency and current you ran your system when testing phantoms etc? You state the range in which it can potentially operate, but not any specific information on what state you used to record your experiments.

I am considering a multi-frequency approach and am trying to determine if the ScouseTom system would be a good platform to base my experiments on.

Any advice and guidance that you could give me would be very much appreciated.

Thanks for your time.

**Comment by tdowrick** [comment]
Hi there,

Thanks for your interest and for the info on the e-mail address, we will fix that.

Most of the details should be in the accompanying paper [here](http://www.mdpi.com/1424-8220/17/2/280), sections 2.2.1 and 2.2.2 give details on the resistor phantom experiments, which used 100uA current between 20Hz and 20kHz. For a typical test we would normally use 1 or 2kHz, but that is more force of habit than for any particular reason.
